package ae.gov.dubaipolice.fajwa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntrvuStrdDtlsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuStrdDtlsAllPropertiesEquals(IntrvuStrdDtls expected, IntrvuStrdDtls actual) {
        assertIntrvuStrdDtlsAutoGeneratedPropertiesEquals(expected, actual);
        assertIntrvuStrdDtlsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuStrdDtlsAllUpdatablePropertiesEquals(IntrvuStrdDtls expected, IntrvuStrdDtls actual) {
        assertIntrvuStrdDtlsUpdatableFieldsEquals(expected, actual);
        assertIntrvuStrdDtlsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuStrdDtlsAutoGeneratedPropertiesEquals(IntrvuStrdDtls expected, IntrvuStrdDtls actual) {
        assertThat(actual)
            .as("Verify IntrvuStrdDtls auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuStrdDtlsUpdatableFieldsEquals(IntrvuStrdDtls expected, IntrvuStrdDtls actual) {
        assertThat(actual)
            .as("Verify IntrvuStrdDtls relevant properties")
            .satisfies(a -> assertThat(a.getStandardOption()).as("check standardOption").isEqualTo(expected.getStandardOption()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuStrdDtlsUpdatableRelationshipsEquals(IntrvuStrdDtls expected, IntrvuStrdDtls actual) {
        assertThat(actual)
            .as("Verify IntrvuStrdDtls relationships")
            .satisfies(a -> assertThat(a.getStandarditem()).as("check standarditem").isEqualTo(expected.getStandarditem()))
            .satisfies(a -> assertThat(a.getAppointment()).as("check appointment").isEqualTo(expected.getAppointment()));
    }
}
