package ae.gov.dubaipolice.fajwa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntrvuReqAttchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuReqAttchAllPropertiesEquals(IntrvuReqAttch expected, IntrvuReqAttch actual) {
        assertIntrvuReqAttchAutoGeneratedPropertiesEquals(expected, actual);
        assertIntrvuReqAttchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuReqAttchAllUpdatablePropertiesEquals(IntrvuReqAttch expected, IntrvuReqAttch actual) {
        assertIntrvuReqAttchUpdatableFieldsEquals(expected, actual);
        assertIntrvuReqAttchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuReqAttchAutoGeneratedPropertiesEquals(IntrvuReqAttch expected, IntrvuReqAttch actual) {
        assertThat(actual)
            .as("Verify IntrvuReqAttch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuReqAttchUpdatableFieldsEquals(IntrvuReqAttch expected, IntrvuReqAttch actual) {
        assertThat(actual)
            .as("Verify IntrvuReqAttch relevant properties")
            .satisfies(a -> assertThat(a.getAddDate()).as("check addDate").isEqualTo(expected.getAddDate()))
            .satisfies(a -> assertThat(a.getAttch()).as("check attch").isEqualTo(expected.getAttch()))
            .satisfies(a -> assertThat(a.getAttchContentType()).as("check attch contenty type").isEqualTo(expected.getAttchContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntrvuReqAttchUpdatableRelationshipsEquals(IntrvuReqAttch expected, IntrvuReqAttch actual) {
        assertThat(actual)
            .as("Verify IntrvuReqAttch relationships")
            .satisfies(a -> assertThat(a.getStandardReqAttach()).as("check standardReqAttach").isEqualTo(expected.getStandardReqAttach()))
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()));
    }
}
