package ae.gov.dubaipolice.fajwa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JobDescAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescAllPropertiesEquals(JobDesc expected, JobDesc actual) {
        assertJobDescAutoGeneratedPropertiesEquals(expected, actual);
        assertJobDescAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescAllUpdatablePropertiesEquals(JobDesc expected, JobDesc actual) {
        assertJobDescUpdatableFieldsEquals(expected, actual);
        assertJobDescUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescAutoGeneratedPropertiesEquals(JobDesc expected, JobDesc actual) {
        assertThat(actual)
            .as("Verify JobDesc auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescUpdatableFieldsEquals(JobDesc expected, JobDesc actual) {
        assertThat(actual)
            .as("Verify JobDesc relevant properties")
            .satisfies(a -> assertThat(a.getJobName()).as("check jobName").isEqualTo(expected.getJobName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobDescUpdatableRelationshipsEquals(JobDesc expected, JobDesc actual) {
        assertThat(actual)
            .as("Verify JobDesc relationships")
            .satisfies(a -> assertThat(a.getStandardType()).as("check standardType").isEqualTo(expected.getStandardType()));
    }
}
