package ae.gov.dubaipolice.fajwa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NominationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNominationAllPropertiesEquals(Nomination expected, Nomination actual) {
        assertNominationAutoGeneratedPropertiesEquals(expected, actual);
        assertNominationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNominationAllUpdatablePropertiesEquals(Nomination expected, Nomination actual) {
        assertNominationUpdatableFieldsEquals(expected, actual);
        assertNominationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNominationAutoGeneratedPropertiesEquals(Nomination expected, Nomination actual) {
        assertThat(actual)
            .as("Verify Nomination auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNominationUpdatableFieldsEquals(Nomination expected, Nomination actual) {
        assertThat(actual)
            .as("Verify Nomination relevant properties")
            .satisfies(a -> assertThat(a.getMachPerc()).as("check machPerc").isEqualTo(expected.getMachPerc()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNominationUpdatableRelationshipsEquals(Nomination expected, Nomination actual) {
        assertThat(actual)
            .as("Verify Nomination relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getJobVacant()).as("check jobVacant").isEqualTo(expected.getJobVacant()));
    }
}
