package ae.gov.dubaipolice.fajwa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StandardCatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardCatAllPropertiesEquals(StandardCat expected, StandardCat actual) {
        assertStandardCatAutoGeneratedPropertiesEquals(expected, actual);
        assertStandardCatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardCatAllUpdatablePropertiesEquals(StandardCat expected, StandardCat actual) {
        assertStandardCatUpdatableFieldsEquals(expected, actual);
        assertStandardCatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardCatAutoGeneratedPropertiesEquals(StandardCat expected, StandardCat actual) {
        assertThat(actual)
            .as("Verify StandardCat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardCatUpdatableFieldsEquals(StandardCat expected, StandardCat actual) {
        assertThat(actual)
            .as("Verify StandardCat relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardCatUpdatableRelationshipsEquals(StandardCat expected, StandardCat actual) {
        assertThat(actual)
            .as("Verify StandardCat relationships")
            .satisfies(a -> assertThat(a.getStandardParent()).as("check standardParent").isEqualTo(expected.getStandardParent()))
            .satisfies(a -> assertThat(a.getReqAttachment()).as("check reqAttachment").isEqualTo(expected.getReqAttachment()));
    }
}
