package ae.gov.dubaipolice.fajwa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StandardParentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardParentAllPropertiesEquals(StandardParent expected, StandardParent actual) {
        assertStandardParentAutoGeneratedPropertiesEquals(expected, actual);
        assertStandardParentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardParentAllUpdatablePropertiesEquals(StandardParent expected, StandardParent actual) {
        assertStandardParentUpdatableFieldsEquals(expected, actual);
        assertStandardParentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardParentAutoGeneratedPropertiesEquals(StandardParent expected, StandardParent actual) {
        assertThat(actual)
            .as("Verify StandardParent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardParentUpdatableFieldsEquals(StandardParent expected, StandardParent actual) {
        assertThat(actual)
            .as("Verify StandardParent relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardParentUpdatableRelationshipsEquals(StandardParent expected, StandardParent actual) {
        assertThat(actual)
            .as("Verify StandardParent relationships")
            .satisfies(a -> assertThat(a.getStandardType()).as("check standardType").isEqualTo(expected.getStandardType()));
    }
}
