package ae.gov.dubaipolice.fajwa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StandardTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardTypeAllPropertiesEquals(StandardType expected, StandardType actual) {
        assertStandardTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertStandardTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardTypeAllUpdatablePropertiesEquals(StandardType expected, StandardType actual) {
        assertStandardTypeUpdatableFieldsEquals(expected, actual);
        assertStandardTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardTypeAutoGeneratedPropertiesEquals(StandardType expected, StandardType actual) {
        assertThat(actual)
            .as("Verify StandardType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardTypeUpdatableFieldsEquals(StandardType expected, StandardType actual) {
        assertThat(actual)
            .as("Verify StandardType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardTypeUpdatableRelationshipsEquals(StandardType expected, StandardType actual) {
        // empty method
    }
}
