package ae.gov.dubaipolice.fajwa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StandardReqAttachAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardReqAttachAllPropertiesEquals(StandardReqAttach expected, StandardReqAttach actual) {
        assertStandardReqAttachAutoGeneratedPropertiesEquals(expected, actual);
        assertStandardReqAttachAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardReqAttachAllUpdatablePropertiesEquals(StandardReqAttach expected, StandardReqAttach actual) {
        assertStandardReqAttachUpdatableFieldsEquals(expected, actual);
        assertStandardReqAttachUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardReqAttachAutoGeneratedPropertiesEquals(StandardReqAttach expected, StandardReqAttach actual) {
        assertThat(actual)
            .as("Verify StandardReqAttach auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardReqAttachUpdatableFieldsEquals(StandardReqAttach expected, StandardReqAttach actual) {
        assertThat(actual)
            .as("Verify StandardReqAttach relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAttDesc()).as("check attDesc").isEqualTo(expected.getAttDesc()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStandardReqAttachUpdatableRelationshipsEquals(StandardReqAttach expected, StandardReqAttach actual) {
        // empty method
    }
}
